# Generated by Django 2.1 on 2019-07-09 06:46

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('jwtapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userdetails',
            managers=[
                ('obeject', django.db.models.manager.Manager()),
            ],
        ),
    ]
